name: opencode

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

jobs:
  opencode:
    if: |
      (
        github.event_name == 'issue_comment' &&
        (
          contains(github.event.comment.body, ' /oc') ||
          startsWith(github.event.comment.body, '/oc') ||
          contains(github.event.comment.body, ' /opencode') ||
          startsWith(github.event.comment.body, '/opencode')
        )
      ) ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run opencode
        uses: sst/opencode/github@latest
        env:
          CHUTES_API_KEY: ${{ secrets.CHUTES_API_KEY }}
        with:
          model: chutes/Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8
